import { builtinModules } from 'node:module'
import esbuild from 'esbuild';
import process from 'process';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin:
https://github.com/kotaindah55/mainstream-icons
*/
`;

const prod = (process.argv[2] === 'production');

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'i18next',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules
	],
	format: 'cjs',
	target: 'es2022',
	logLevel: 'info',
	treeShaking: true,
	sourcemap: prod ? false : 'inline',
	outfile: 'dist/main.js',
	minify: prod,
	dropLabels: prod ? ['DEVEL'] : [],
	tsconfig: 'tsconfig.json'
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}